# Generated by Django 3.0.5 on 2020-05-02 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20200502_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='festivalgoods',
            name='desc',
            field=models.CharField(max_length=200, null=True, verbose_name='描述'),
        ),
    ]
