"""
Django settings for niu_she_bing project.

Generated by 'django-admin startproject' using Django 3.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'swkzc=xwd76gh%k9tv=(nru!!tq^fj)4!&!1k1foir6(#4u4gd'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bg',
    'common',
    'fg_m',
    'fg_pc',
    'scheduler'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'fg_pc.middleware.AuthMiddleware'
]

ROOT_URLCONF = 'niu_she_bing.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'niu_she_bing.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases
ENV_PROFILE = os.getenv("ENV")
if ENV_PROFILE == 'PRODUCTION':
    DATABASES = {
        'default': {
            'ENGINE': 'niu_she_bing.mysql',
            'NAME': 'niushebing',
            'USER': 'nsb',
            'PASSWORD': '123456',
            'HOST': '11ms.cn',
            'PORT': '3306',
            'POOL_SIZE': 20,  # 每个进程的连接池的大小，总连接数=20*总进程数
            'STORAGE_ENGINE': 'INNODB',
            'CHARSET': 'utf-8',
            'CONN_MAX_AGE': 28790,  # 比mysql默认的wait_timeout小10秒
            'OPTIONS': {
                'init_command': 'SET default_storage_engine=INNODB',
            }
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'niu_she_bing.mysql',
            'NAME': 'niushebing',
            'USER': 'www',
            'PASSWORD': '123456',
            'HOST': '127.0.0.1',
            'PORT': '3306',
            'POOL_SIZE': 20,  # 每个进程的连接池的大小，总连接数=20*总进程数
            'STORAGE_ENGINE': 'INNODB',
            'CHARSET': 'utf-8',
            'CONN_MAX_AGE': 28790,  # 比mysql默认的wait_timeout小10秒
            'OPTIONS': {
                'init_command': 'SET default_storage_engine=INNODB',
            }
        }
    }


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'

log_path = os.path.join(BASE_DIR, 'logs')
os.makedirs(log_path, 666, True)
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '%(asctime)s [%(threadName)s:%(thread)5d] [%(levelname)-5s] [%(filename)-10s:%(lineno)d] [%(module)s:%(funcName)s]- %(message)s'
        },
        'simple': {
            'format': '%(asctime)s [%(levelname)-5s] [%(filename)-10s:%(lineno)3d]- %(message)s'
        }
    },
    'filters': {
    },
    'handlers': {
        'info_file_handler': {
            'level': 'INFO',
            'class': 'niu_she_bing.patch.MultiProcessSafeDailyRotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs/info'),
            'encoding': 'utf8',
            'when': 'D',
            'backupCount': 10,
            'interval': 1,
            'formatter': 'verbose'
        },
        'err_file_handler': {
            'level': 'ERROR',
            'class': 'niu_she_bing.patch.MultiProcessSafeDailyRotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs/error'),
            'encoding': 'utf8',
            'when': 'D',
            'backupCount': 30,
            'interval': 1,
            'formatter': 'verbose'
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['info_file_handler', 'err_file_handler', 'console'],
            'level': 'INFO',
            'propagate': True  # 是否继承父类的log信息
        },
    }
}
